# Generated by Django 4.1.2 on 2023-06-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('cashier', 'cashier'), ('nurse', 'nurse')], max_length=50, null=True),
        ),
    ]
