# Generated by Django 4.1.2 on 2023-06-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accountmodel_avatar_alter_accountmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('cashier', 'cashier'), ('nurse', 'nurse'), ('client', 'client')], max_length=50, null=True),
        ),
    ]
