# Generated by Django 4.1.2 on 2022-10-15 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_block', models.CharField(blank=True, max_length=200, null=True)),
                ('room_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('room_package', models.CharField(blank=True, max_length=200, null=True)),
                ('room_price', models.CharField(blank=True, max_length=200, null=True)),
                ('boarding_package', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='FREE', max_length=200, null=True)),
            ],
        ),
       
    ]
