# Generated by Django 4.1.2 on 2022-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_roomsbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsbooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomsbooking',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
